CREATE DATABASE IF NOT EXISTS tccmatcher;
use tccmatcher;

DROP TABLE IF EXISTS MOCK_DATA;

create table MOCK_DATA ( 
    id INT NOT NULL,
    first_name VARCHAR(200) NOT NULL,
    last_name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    gender VARCHAR(100) NOT NULL,
    psw VARCHAR(100) NOT NULL
);

insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (1, 'Hephzibah', 'Caulket', 'hcaulket0@over-blog.com', 'Female', 'scXwqut');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (2, 'Christy', 'Amoss', 'camoss1@forbes.com', 'Male', 'Asji8V');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (3, 'Rice', 'Pellatt', 'rpellatt2@deviantart.com', 'Non-binary', 'CCcRjcUeXf8');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (4, 'Mart', 'Dowglass', 'mdowglass3@illinois.edu', 'Polygender', 'veRmkDaLmY8f');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (5, 'Gerti', 'Craik', 'gcraik4@archive.org', 'Bigender', 'gaj89O');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (6, 'Julita', 'Redgewell', 'jredgewell5@cam.ac.uk', 'Genderfluid', 'yjh7yYGuP');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (7, 'Harald', 'Pitchers', 'hpitchers6@mediafire.com', 'Bigender', 'CIJYNL1lI9');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (8, 'Faun', 'Boanas', 'fboanas7@discuz.net', 'Polygender', 'leW8Ha3kXyc');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (9, 'Curry', 'Dadge', 'cdadge8@elegantthemes.com', 'Polygender', 'ZlWgzz9HFHX');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (10, 'Corrinne', 'Oldman', 'coldman9@jiathis.com', 'Genderfluid', 'iJ35ac');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (11, 'Nikolia', 'Tomankiewicz', 'ntomankiewicza@wired.com', 'Genderfluid', 'cYRBVDW9');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (12, 'Casi', 'McPake', 'cmcpakeb@theguardian.com', 'Genderqueer', '0bPUG6');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (13, 'Glynis', 'Drennan', 'gdrennanc@amazon.de', 'Female', 'huuASfMo');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (14, 'Raquel', 'Stubs', 'rstubsd@mozilla.com', 'Non-binary', 'OjxBiOMH4');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (15, 'Case', 'Minney', 'cminneye@domainmarket.com', 'Genderqueer', '1Q9PCI');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (16, 'Wait', 'Oganian', 'woganianf@yellowbook.com', 'Male', 'YuPFkzO4ROO');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (17, 'Shane', 'Pring', 'springg@gov.uk', 'Genderfluid', 'ZB7bKzPM5');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (18, 'Aldous', 'Vockins', 'avockinsh@etsy.com', 'Genderqueer', '0qnSurGCnfz');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (19, 'Lawry', 'Tomkys', 'ltomkysi@latimes.com', 'Female', '8wBPWBldmKeD');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (20, 'Jsandye', 'Detloff', 'jdetloffj@yellowbook.com', 'Non-binary', 'As59gD');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (21, 'Bamby', 'Real', 'brealk@dell.com', 'Agender', 'FjS98kYN');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (22, 'Itch', 'Kondrachenko', 'ikondrachenkol@vkontakte.ru', 'Non-binary', '9TfApx');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (23, 'Arlene', 'Powling', 'apowlingm@census.gov', 'Agender', 'eC9YiYv');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (24, 'Zarla', 'Bellew', 'zbellewn@ihg.com', 'Polygender', '7tsSqW');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (25, 'Ondrea', 'Uccello', 'ouccelloo@mac.com', 'Female', 'XATrfs');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (26, 'Montgomery', 'Keaton', 'mkeatonp@fema.gov', 'Non-binary', 'obZwzmRfwBQv');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (27, 'Estele', 'Quaif', 'equaifq@scribd.com', 'Polygender', 'A087pxb6');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (28, 'Hanni', 'Moxsom', 'hmoxsomr@kickstarter.com', 'Male', 'WHx6UIB2yE');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (29, 'Jennee', 'Roskruge', 'jroskruges@accuweather.com', 'Genderfluid', 'Yby7Aiq5C');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (30, 'Jodie', 'Bonas', 'jbonast@ucoz.ru', 'Bigender', 'vIOxMI6ArW5');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (31, 'Tiphani', 'Redon', 'tredonu@businessinsider.com', 'Bigender', '5XvefqKddArd');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (32, 'Diandra', 'Baskerfield', 'dbaskerfieldv@histats.com', 'Polygender', 'AvmITpxEzm');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (33, 'Margaux', 'Brisland', 'mbrislandw@last.fm', 'Bigender', 'UWEOEt');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (34, 'Dorry', 'Lagadu', 'dlagadux@stanford.edu', 'Non-binary', 'q3S7x6VRe4DK');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (35, 'Gustavus', 'Lennox', 'glennoxy@godaddy.com', 'Bigender', 'O0PdcbXO');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (36, 'Charla', 'Dansie', 'cdansiez@cmu.edu', 'Male', '1lvJxksgJ');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (37, 'Donia', 'Dudliston', 'ddudliston10@nhs.uk', 'Male', 'yTYRNuhi');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (38, 'Wilton', 'Duffit', 'wduffit11@nifty.com', 'Male', 'lzNxbeejJ');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (39, 'Bone', 'Dalloway', 'bdalloway12@cargocollective.com', 'Non-binary', 'stW25SBreX');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (40, 'Benny', 'Doding', 'bdoding13@prlog.org', 'Agender', 'MMur6a');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (41, 'Franklin', 'Harrowsmith', 'fharrowsmith14@github.com', 'Genderfluid', 'n6SQVCi8e');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (42, 'Selma', 'Starrs', 'sstarrs15@wordpress.org', 'Agender', '5IdLOei');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (43, 'Wilbert', 'Borkin', 'wborkin16@usa.gov', 'Agender', 'PKhPBHIyXZIF');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (44, 'Rosemonde', 'Spinnace', 'rspinnace17@taobao.com', 'Female', '2bPiMelsppR3');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (45, 'Vidovic', 'Daltrey', 'vdaltrey18@unesco.org', 'Polygender', 'd2NKzoSC');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (46, 'Spense', 'Kopfer', 'skopfer19@acquirethisname.com', 'Agender', 'upi8wxgYWvw');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (47, 'Dilly', 'Spencer', 'dspencer1a@bbb.org', 'Bigender', 'RGyxb6K');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (48, 'Lucina', 'Soonhouse', 'lsoonhouse1b@bloglovin.com', 'Bigender', '7FjRUKhyEU');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (49, 'Kania', 'Smithers', 'ksmithers1c@arstechnica.com', 'Genderqueer', 'wal4rFnrF');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (50, 'Byrann', 'Tevelov', 'btevelov1d@arstechnica.com', 'Genderfluid', 'UvBPQj');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (51, 'Davon', 'Wheatcroft', 'dwheatcroft1e@globo.com', 'Male', 'U2Ss4G');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (52, 'Sylas', 'Galfour', 'sgalfour1f@sourceforge.net', 'Polygender', 'hEQadOL');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (53, 'Heinrik', 'Dresser', 'hdresser1g@japanpost.jp', 'Female', 'PQURYMIZ2r');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (54, 'Miguela', 'Stiller', 'mstiller1h@sourceforge.net', 'Female', 'm4FntPNzcu4S');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (55, 'Eve', 'Tortoise', 'etortoise1i@ft.com', 'Genderqueer', 'ZqqlBThF');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (56, 'Glenda', 'Hunnicutt', 'ghunnicutt1j@mysql.com', 'Bigender', 'R1i7zXJle');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (57, 'Vera', 'Cheetham', 'vcheetham1k@theglobeandmail.com', 'Female', 'CItCBM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (58, 'Sofia', 'De Bellis', 'sdebellis1l@cdc.gov', 'Agender', 'CVn149SbC9k');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (59, 'Chen', 'Eisak', 'ceisak1m@moonfruit.com', 'Agender', 'UstnxpL');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (60, 'Eadith', 'Lippini', 'elippini1n@uol.com.br', 'Genderqueer', 'XZOiMCW');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (61, 'Terri', 'Mollett', 'tmollett1o@netlog.com', 'Non-binary', '8QCm8LaJ1i');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (62, 'Ingra', 'Tempest', 'itempest1p@163.com', 'Genderfluid', '7AD354Ca0O');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (63, 'Andy', 'Pavlik', 'apavlik1q@canalblog.com', 'Non-binary', 'io4cb5Opf5');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (64, 'Benton', 'Davidy', 'bdavidy1r@comsenz.com', 'Female', 'Z3P8ZT');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (65, 'Debbi', 'Prettjohn', 'dprettjohn1s@tinyurl.com', 'Agender', 'hC58VQ5YT');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (66, 'Darnall', 'Buckthorp', 'dbuckthorp1t@g.co', 'Genderqueer', 'yKTWgp0jLut');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (67, 'Ilaire', 'Haycox', 'ihaycox1u@usgs.gov', 'Non-binary', 'AiYzByplCW');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (68, 'Patrizia', 'Tutin', 'ptutin1v@amazon.de', 'Female', 'P7z3LOn');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (69, 'Holden', 'Samme', 'hsamme1w@house.gov', 'Non-binary', 'KnWjx86lM');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (70, 'Adelind', 'Lark', 'alark1x@youtube.com', 'Genderqueer', 'L2nRUTigfz');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (71, 'Salomone', 'Alebrooke', 'salebrooke1y@china.com.cn', 'Agender', 'kVBdxDrXb');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (72, 'Lianne', 'Ablitt', 'lablitt1z@google.fr', 'Male', 'BgeDaZ8b');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (73, 'Aimee', 'Manville', 'amanville20@europa.eu', 'Non-binary', 'sKkm85SH');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (74, 'Anatol', 'Jeskin', 'ajeskin21@ihg.com', 'Female', 'a3jjwNh');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (75, 'Harrison', 'Pawle', 'hpawle22@tumblr.com', 'Bigender', 'p8eppAa');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (76, 'Sadella', 'Magill', 'smagill23@washington.edu', 'Polygender', 'PcMKDxfzEc');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (77, 'Abner', 'Ormesher', 'aormesher24@dailymail.co.uk', 'Bigender', 'Ml5hdbJ98A');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (78, 'Rhona', 'Muggleston', 'rmuggleston25@oracle.com', 'Female', 'KlHjRLrvO');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (79, 'Windham', 'McMichan', 'wmcmichan26@hubpages.com', 'Female', 'NvyhSRZtv');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (80, 'Gabbie', 'Boldero', 'gboldero27@freewebs.com', 'Male', 'b0mAh3NgNKx');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (81, 'Ramonda', 'Livings', 'rlivings28@flickr.com', 'Genderqueer', 'EsQxwGMu9ACF');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (82, 'Kasper', 'Evert', 'kevert29@google.ru', 'Bigender', 'lU9obz742F');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (83, 'Winn', 'Shapland', 'wshapland2a@springer.com', 'Non-binary', 'r8n2clZskb8D');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (84, 'Jerry', 'Allman', 'jallman2b@51.la', 'Female', 'gxk93i6R');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (85, 'Lauri', 'Tureville', 'ltureville2c@census.gov', 'Polygender', '2uIpjY');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (86, 'Ketty', 'Le Gassick', 'klegassick2d@sun.com', 'Non-binary', 'dFP2mlPRy');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (87, 'Abbot', 'Stave', 'astave2e@discovery.com', 'Male', 'j7jW69');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (88, 'Rica', 'Liddyard', 'rliddyard2f@joomla.org', 'Bigender', 'jg4tCSk');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (89, 'Casie', 'Manilove', 'cmanilove2g@google.com.au', 'Non-binary', '9jr74j');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (90, 'Oswell', 'Mathie', 'omathie2h@mail.ru', 'Polygender', 'vQa9ev');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (91, 'Daloris', 'Garretson', 'dgarretson2i@globo.com', 'Genderfluid', 'obQCvWCeZsMl');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (92, 'Lynnelle', 'Penright', 'lpenright2j@mozilla.com', 'Female', '1iCZdje9tDc');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (93, 'Hy', 'Moden', 'hmoden2k@angelfire.com', 'Male', '6aWq3J');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (94, 'Mel', 'Lambe', 'mlambe2l@soundcloud.com', 'Male', '7VjW02pbtOv3');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (95, 'Sophia', 'Brigshaw', 'sbrigshaw2m@aboutads.info', 'Female', 'a5XHqEnGB');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (96, 'Alayne', 'Petruskevich', 'apetruskevich2n@addtoany.com', 'Bigender', 'EGKpHKOR');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (97, 'Bobby', 'Surcombe', 'bsurcombe2o@sciencedirect.com', 'Bigender', 'HBVLg5');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (98, 'Kippie', 'Corn', 'kcorn2p@uol.com.br', 'Genderfluid', 'ijONiWlEmvqo');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (99, 'Brion', 'Ohlsen', 'bohlsen2q@angelfire.com', 'Agender', 'x3LHrwSs');
insert into MOCK_DATA (id, first_name, last_name, email, gender, psw) values (100, 'Clio', 'Huniwall', 'chuniwall2r@webeden.co.uk', 'Genderfluid', 'XmGO0W8jBQ6');
